[window]
# window title
title = "Exp Check"
# window dimensions "<width>x<height>+<x position>+<y position>"
geometry = "800x500+500+300"
# arguments to window config
config = {}
# global theme to apply to all widgets
theme = {}
# configure grid sizing and weight
grid = {row = {}, column = {}}

[widgets]
[widgets.add_button]
type = "button"
init = {}
grid = {}

